"""create_all_tables

Revision ID: 06a94ed61647
Revises: 
Create Date: 2026-04-08 07:35:30.242755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a94ed61647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_members',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('weekly_hour_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('color_tag', sa.Text(), server_default='#3B82F6', nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.CheckConstraint('weekly_hour_limit > 0', name='ck_members_positive_hours'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_preferences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('general_weekly_hour_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('preferences_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default='{"min_rest_hours": 12, "max_consecutive_days": 6, "allow_weekend_work": true, "prefer_balanced_distribution": true, "fill_unassigned_only": true}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('general_weekly_hour_limit > 0', name='ck_gen_prefs_positive_hours'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('schedule_period_id', sa.BigInteger(), nullable=False),
    sa.Column('executed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('input_snapshot_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_runs_period_id', 'generation_runs', ['schedule_period_id'], unique=False)
    op.create_index('ix_generation_runs_user_id', 'generation_runs', ['executed_by_user_id'], unique=False)
    op.create_table('member_generation_preferences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('preferences_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index('ix_member_gen_prefs_member_id', 'member_generation_preferences', ['member_id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('schedule_period_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('assignment_source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('details_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assignment_source IN ('manual', 'auto', 'template')", name='ck_assignments_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_period_id', 'member_id', 'date', name='uq_assignments_period_member_date')
    )
    op.create_index('ix_assignments_member_date', 'schedule_assignments', ['member_id', 'date'], unique=False)
    op.create_index('ix_assignments_member_id', 'schedule_assignments', ['member_id'], unique=False)
    op.create_index('ix_assignments_period_id', 'schedule_assignments', ['schedule_period_id'], unique=False)
    op.create_index('ix_assignments_shift_type_id', 'schedule_assignments', ['shift_type_id'], unique=False)
    op.create_table('schedule_periods',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('generation_summary_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active')", name='ck_periods_status'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_periods_month'),
    sa.CheckConstraint('start_date <= end_date', name='ck_periods_date_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_periods_created_by', 'schedule_periods', ['created_by_user_id'], unique=False)
    op.create_index('ix_schedule_periods_year_month', 'schedule_periods', ['year', 'month'], unique=False)
    op.create_table('shift_types',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('default_start_time', sa.Time(), nullable=True),
    sa.Column('default_end_time', sa.Time(), nullable=True),
    sa.Column('counts_as_work_time', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('color', sa.Text(), server_default='#6B7280', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("category IN ('work', 'vacation', 'special')", name='ck_shift_types_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('shift_types')
    op.drop_index('ix_schedule_periods_year_month', table_name='schedule_periods')
    op.drop_index('ix_schedule_periods_created_by', table_name='schedule_periods')
    op.drop_table('schedule_periods')
    op.drop_index('ix_assignments_shift_type_id', table_name='schedule_assignments')
    op.drop_index('ix_assignments_period_id', table_name='schedule_assignments')
    op.drop_index('ix_assignments_member_id', table_name='schedule_assignments')
    op.drop_index('ix_assignments_member_date', table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index('ix_member_gen_prefs_member_id', table_name='member_generation_preferences')
    op.drop_table('member_generation_preferences')
    op.drop_index('ix_generation_runs_user_id', table_name='generation_runs')
    op.drop_index('ix_generation_runs_period_id', table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_table('generation_preferences')
    op.drop_table('department_members')
    # ### end Alembic commands ###
