"""add_is_active_to_schedule_periods

Revision ID: 430667857ba4
Revises: b81b2267fdbf
Create Date: 2026-04-10 10:29:04.960238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430667857ba4'
down_revision: Union[str, Sequence[str], None] = 'b81b2267fdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_periods', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_periods', 'is_active')
    # ### end Alembic commands ###
