"""add_foreign_key_constraints

Revision ID: b81b2267fdbf
Revises: 6dd228d9f2c3
Create Date: 2026-04-10 10:26:33.465964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81b2267fdbf'
down_revision: Union[str, Sequence[str], None] = '6dd228d9f2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'generation_runs', 'users', ['executed_by_user_id'], ['id'])
    op.create_foreign_key(None, 'generation_runs', 'schedule_periods', ['schedule_period_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'member_generation_preferences', 'department_members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'schedule_assignments', 'shift_types', ['shift_type_id'], ['id'])
    op.create_foreign_key(None, 'schedule_assignments', 'schedule_periods', ['schedule_period_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedule_assignments', 'department_members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'schedule_periods', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_periods', type_='foreignkey')
    op.drop_constraint(None, 'schedule_assignments', type_='foreignkey')
    op.drop_constraint(None, 'schedule_assignments', type_='foreignkey')
    op.drop_constraint(None, 'schedule_assignments', type_='foreignkey')
    op.drop_constraint(None, 'member_generation_preferences', type_='foreignkey')
    op.drop_constraint(None, 'generation_runs', type_='foreignkey')
    op.drop_constraint(None, 'generation_runs', type_='foreignkey')
    # ### end Alembic commands ###
